name: Python CI 

on: # when to run this action file
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  checks: # This is a job, name is arbitrary
    runs-on: ubuntu-latest # Every job needs 'runs-on'
    steps: # The steps for each job
      - name: GitHub is checking out code... # Name is optional here
        uses: actions/checkout@v5

      - name: Setup Python Environment # Another step
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Navigate to app # Another step
        run: cd oo-lib-py/
        
      - name: Install pytest # Another step
        run: python3 -m pip install -U pytest

      - name: Run tests # Another step
        run: python3 -m pytest
